name = "ip-card-worker"
main = "src/worker.js"
compatibility_date = "2023-10-25"

# 绑定 D1 数据库
[[d1_databases]]
binding = "DB" # 代码里用 env.DB 调用
database_name = "ip-card-db"
database_id = "替换成你的D1_DATABASE_ID"